Remove developer stdout debug message
greenplum-db/gpupgrade pull request #768
Opened 2023-03-06 23:15 UTC by jimmyyih

When running initialize, we see this output:
```
Proceeding with upgrade
Starting gpupgrade hub process...                                  [IN PROGRESS]Started hub
Starting gpupgrade hub process...                                  [COMPLETE]
Saving source cluster configuration...                             [COMPLETE]
```

The "Started hub" part doesn't seem like it should be there and messes with the IN PROGRESS to COMPLETE line replacement. With this patch, it'll now look like this:
```
Proceeding with upgrade
Starting gpupgrade hub process...                                  [COMPLETE]
Saving source cluster configuration...                             [COMPLETE]
```

2023-03-06 23:59 UTC, kalensk requested changes
This also removes "Started hub" when the user runs "gpupgrade kill-services". The required change is more complicated.

2023-03-07 23:37 UTC, jimmyyih commented
> This also removes "Started hub" when the user runs "gpupgrade restart-services". We want to preserve that message for restart-services. The required change is a bit more complicated.

Good catch.  Made the suggested change.

2023-03-08 23:43 UTC, kalensk approved these changes
Looks good! Thanks for making the change : )

(Note: For a future PR or similar. Just making an observation. During my limited testing I noticed `gpupgrade restart-services` print `Restarted agents on:` even if there are no agents to restart. That should probably be conditionalized and maybe add another message saying nothing to restart or all good or something for the user.)

2023-03-08 23:44 UTC, kalensk commented
Can probably close GPUP-62

2023-03-16 21:59 UTC, merged